# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test',
                'doc_host': 'https://jmacarulla.github.io',
                'git_url': 'https://github.com/jmacarulla/nbdev-test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.core': { 'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py'),
                                 'nbdev_test.core.sum': ('core.html#sum', 'nbdev_test/core.py')}}}