# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'my_sum', 'my_sub', 'my_mul', 'say_hello']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 4
def my_sum(x): return x+22

# %% ../nbs/00_core.ipynb 5
def my_sub(x): return x-22
def my_mul(x): return x*22

# %% ../nbs/00_core.ipynb 6
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
